function R_out=R(eul)
Rx=[1 0 0;...
0 cos(eul(1)) -sin(eul(1));...
0 sin(eul(1)) cos(eul(1))];

Ry=[cos(eul(2)) 0 sin(eul(2));...
0 1 0;...
-sin(eul(2)) 0 cos(eul(2))];

Rz=[cos(eul(3)) -sin(eul(3)) 0;...
    sin(eul(3)) cos(eul(3)) 0;...
    0 0 1];

R_out= Rx*Ry*Rz;



end